# Site settings
title: JungJin Park
name: JungJin Park

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/Mids
 - title: LinkedIn
   url: https://www.linkedin.com/in/midsin/

#Any buzzword skills you want to include
skills:
 - Game Development
 - Open Source
 - Design Patterns
 - Game Design
 - OpenGL
 - C++
 - C#
 - Unity 3D
 - Unreal Engine 4
 - Python
 - Java
 - Android

#Work experience is required
roles:
 - title: Researcher
   start: Sep 2017
   end: Ongoing
   employer: Computer Graphics & Animation Lab
   description: Research Lab in graduate school
 - title: Information Management Officer
   start: Jan 2014
   end: Aug 2015
   employer: U.S. Army Criminal Investigation Command
   description: Korean Augmentation to the United States Army
 - title: Android application developer
   start: Apr 2013
   end: Oct 2013
   employer: Friberry
   description: Made an Android app for HotPick, Overseas purchasing service
   
#Education is required
education:
 - level: Master's degree
   date: 2020 (Ongoing)
   subject: Computer Science
   school: Hanyang University
 - level: Bachelor's degree
   date: 2017
   subject: Computer Science
   school: Hanyang University

#List of interesting Github repo/projects to include - optional
github:
 - Mids/3DGunscape
 - Mids/Procedural-Room-Dungeon-Generator
 - Mids/Sions-X
 - Mids/Korea-Random-Defence

intro: |
  I like to develop 3D video games. Currently interested in Procedural Contents Generation and RNN.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   TBA
